# requires lib3mf being build without asan (see README.md for the script) 
afl:
		afl-clang-fast++ -g -O1 -fno-omit-frame-pointer -I./lib3mf/Autogenerated/Bindings/Cpp/   
		test.cpp -L./lib3mf -l3mf -o test_afl -Wl,-rpath,$(realpath ./lib3mf)

# requires lib3mf being build with asan (see README.md for the script) 
afl_asan:
		afl-clang-fast++ -g -O1 -fno-omit-frame-pointer -fsanatize=address -I./lib3mf/Autogenerated/Bindings/Cpp/   
		test.cpp -L./lib3mf -l3mf -o test_afl_asan -Wl,-rpath,$(realpath ./lib3mf)

# requires lib3mf being build without asan (see README.md for the script) 
honggfuzz:
		hfuzz-clang++ -g -O1 -fno-omit-frame-pointer -I./lib3mf/Autogenerated/Bindings/Cpp/                                 
		test.cpp -L./lib3mf/build -l3mf -o test_hf -Wl,-rpath,$(realpath ./lib3mf/build)

# requires lib3mf being build with asan (see README.md for the script) 
honggfuzz_asan:
		hfuzz-clang++ -g -O1 -fno-omit-frame-pointer -fsanatize=address -I./lib3mf/Autogenerated/Bindings/Cpp/                                 		  test.cpp -L./lib3mf/build -l3mf -o test_hf_asan -Wl,-rpath,$(realpath ./lib3mf/build)

# requires lib3mf being build without asan (see README.md for the script) 
zuff:
		clang++ -g -O1 -fno-omit-frame-pointer -I./lib3mf/Autogenerated/Bindings/Cpp/   
		test.cpp -L./lib3mf -l3mf -o test_zzuf -Wl,-rpath,$(realpath ./lib3mf)

# requires lib3mf being build with asan (see README.md for the script) 
zuff_asan:
		clang++ -g -O1 -fno-omit-frame-pointer -fsanatize=address -I./lib3mf/Autogenerated/Bindings/Cpp/   
		test.cpp -L./lib3mf -l3mf -o test_zzuf_asan -Wl,-rpath,$(realpath ./lib3mf)

run_afl:
		afl-fuzz -i in/ -o out -- ./test @@

run_hf:
		honggfuzz -i in --output out_hf_asan --timeout 10000 -P --threads 1 -- ./test_hf ___FILE___

run_zzuf:
		./zzuf.sh

run_zuff_asan:
		./zzuf_asan.sh

clean: 
		rm -f test_afl test_afl_asan test_hf test_hf_asan test_zzuf test_zzuf_asan
